services:
  fazcord:
    image: ghcr.io/fazuh/fazcord:latest
    container_name: fazcord
    build:
      dockerfile: docker/Dockerfile.fazcord
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql # Override .env
    env_file: .env
    depends_on:
      - mysql
    networks:
      - faz-network
    volumes:
      - ./logs:/app/logs

  fazcollect:
    image: ghcr.io/fazuh/fazcollect:latest
    container_name: fazcollect
    build:
      dockerfile: docker/Dockerfile.fazcollect
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql # Override .env
    env_file: .env
    depends_on:
      - mysql
    expose:
      - 8000
    networks:
      - faz-network
    volumes:
      - ./logs:/app/logs

  mysql:
    image: mariadb:11.4.2
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - faz-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mysql
    networks:
      - faz-network

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

networks:
  faz-network:
