FROM python:3.12.4-slim

WORKDIR /app

COPY asset ./asset
COPY fazbot ./fazbot
COPY fazutil ./fazutil
COPY .env .
COPY requirements_fazbot.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "fazbot"]
