"""1.1.0 Improve fazdb relationships

Revision ID: 3173276fb06a
Revises: 3965042b4d49
Create Date: 2024-10-27 19:10:08.450598

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3173276fb06a"
down_revision: Union[str, None] = "3965042b4d49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# fmt: off
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f("fk_player_history_uuid_player_info"), "player_history", "player_info", ["uuid"], ["uuid"],)
    op.create_foreign_key(op.f("fk_guild_history_name_guild_info"), "guild_history", "guild_info", ["name"], ["name"],)
    op.create_foreign_key(op.f("fk_character_history_character_uuid_character_info"), "character_history", "character_info", ["character_uuid"], ["character_uuid"],)
    op.create_foreign_key(op.f("fk_character_info_uuid_player_info"), "character_info", "player_info", ["uuid"], ["uuid"],)
    op.create_index(op.f("ix_character_history_character_uuid"), "character_history", ["character_uuid"], unique=False,)
    op.create_index(op.f("ix_guild_history_name"), "guild_history", ["name"], unique=False)
    op.create_index(op.f("ix_guild_member_history_uuid"), "guild_member_history", ["uuid"], unique=False,)
    op.create_index(op.f("ix_player_history_uuid"), "player_history", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_player_history_uuid_player_info"), "player_history", type_="foreignkey")
    op.drop_index(op.f("ix_player_history_uuid"), table_name="player_history")
    op.drop_index(op.f("ix_guild_member_history_uuid"), table_name="guild_member_history")
    op.drop_constraint(op.f("fk_guild_history_name_guild_info"), "guild_history", type_="foreignkey")
    op.drop_index(op.f("ix_guild_history_name"), table_name="guild_history")
    op.drop_constraint( op.f("fk_character_info_uuid_player_info"),"character_info", type_="foreignkey")
    op.drop_constraint(op.f("fk_character_history_character_uuid_character_info"), "character_history", type_="foreignkey",)
    op.drop_index(op.f("ix_character_history_character_uuid"), table_name="character_history")
    # ### end Alembic commands ###
# fmt: on
