services:
  fazbot:
    image: ghcr.io/fazuh/fazbot:latest
    container_name: fazbot
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: faz
      MYSQL_PASSWORD: password
      MYSQL_FAZBOT_DATABASE: faz-bot
      MYSQL_FAZDB_DATABASE: faz-db
    env_file: ../.env
    depends_on:
      - mysql
    networks:
      - faz-network
    volumes:
      - ../logs/fazbot:/app/logs

  fazdb:
    image: ghcr.io/fazuh/fazdb:latest
    container_name: fazdb
    build:
      context: ..
      dockerfile: docker/Dockerfile.db
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: faz
      MYSQL_PASSWORD: password
      MYSQL_FAZDB_DATABASE: faz-db
    env_file: ../.env
    depends_on:
      - mysql
    expose:
      - 8000
    networks:
      - faz-network
    volumes:
      - ../logs/fazdb:/app/logs

  mysql:
    image: mariadb:11.4.2
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_FAZBOT_DATABASE: fazbot
      MYSQL_FAZDB_DATABASE: fazdb
    expose:
      - 3306
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/init:/docker-entrypoint-initdb.d
    networks:
      - faz-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: faz
      PMA_PASSWORD: password
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mysql
    networks:
      - faz-network

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus

networks:
  faz-network:
