FROM python:3.13.0-slim

WORKDIR /app

COPY fazbeat/fazcollect ./fazbeat/fazcollect
COPY fazutil ./fazutil
COPY requirements-fazcollect.txt requirements.txt

COPY scripts ./scripts
COPY alembic.ini alembic.ini
COPY mysql/vcs ./mysql/vcs

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && pip3 install --no-cache-dir -r requirements.txt

CMD ["./scripts/safestart.sh", "fazbeat.fazcollect", ">=1.1.0,<1.2", "faz-wynn", "FAZCOLLECT_DISCORD_LOG_WEBHOOK"]
