FROM python:3.12.7-slim

WORKDIR /app

COPY fazbeat/api_collect ./fazbeat/api_collect
COPY fazutil ./fazutil
COPY requirements-api_collect.txt requirements.txt

COPY scripts ./scripts
COPY alembic.ini alembic.ini
COPY mysql/vcs ./mysql/vcs

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && pip3 install --no-cache-dir -r requirements.txt

CMD ["./scripts/safestart.sh", "fazbeat.api_collect", ">=1.1.0,<1.2", "faz-db", "API_COLLECT_DISCORD_LOG_WEBHOOK"]
