FROM python:3.12.4-slim

WORKDIR /app

COPY fazcord ./fazcord
COPY fazutil ./fazutil
COPY requirements-fazcord.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "fazcord"]
