FROM python:3.13.0-slim

WORKDIR /app

COPY fazcord ./fazcord
COPY fazutil ./fazutil
COPY requirements-fazcord.txt requirements.txt

COPY scripts ./scripts
COPY alembic.ini alembic.ini
COPY mysql/vcs ./mysql/vcs

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && pip3 install --no-cache-dir -r requirements.txt

CMD ["./scripts/_safestart.sh", "fazcord", ">=1.0.0,<1.1 >=1.1.0,<1.2", "faz-cord faz-wynn", "FAZCORD_DISCORD_LOG_WEBHOOK FAZCOLLECT_DISCORD_LOG_WEBHOOK"]
