# Credit: Workflow configs inspired from https://github.com/Wynntils/Wynntils

name: Autopromote branches

on:
  push:
    branches:
      - main

jobs:
  update-release:
    if: github.ref == 'refs/heads/main'
    name: Merge main into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          source: "main"
          target: "release"
