name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: FAZuH
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push fazbot
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.bot
          platforms: linux/amd64
          push: true
          tags: ghcr.io/fazuh/fazbot:latest

      - name: Build and Push fazdb
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.db
          platforms: linux/amd64
          push: true
          tags: ghcr.io/fazuh/fazdb:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [image]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: ssh -o LogLevel=QUIET -t ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "/srv/faz-bot/docker/deploy.sh"
