# Credit: Workflow configs inspired from Wynntils and moto-bot
name: Python Format & Test

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main, development]

jobs:
  format-and-test:
    name: Run Python Tests
    if: "! github.event.pull_request.draft"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stop default MySQL server (if any)
        run: sudo service mysql stop

      - name: Setup MariaDB
        run: |
          docker run \
          -e MYSQL_ROOT_PASSWORD=password \
          -e MYSQL_USER=faz \
          -e MYSQL_PASSWORD=password \
          -e MYSQL_FAZCORD_DATABASE=faz-cord_test \
          -e MYSQL_FAZDB_DATABASE=faz-db_test \
          -v ${GITHUB_WORKSPACE}/mysql/init:/docker-entrypoint-initdb.d \
          -d -p "3306:3306" mariadb:11.4.2

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black
          pip install -r requirements_dev.txt

      - name: Format with Black
        run: black .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "faz-bot-bot"
          commit_user_email: "fazuhhh@proton.me"
          commit_message: "ci: spotless formatting"

      # NOTE: Make sure tests still works even with placeholder .env values
      - name: Test with pytest
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_USER: faz
          MYSQL_PASSWORD: password
          MYSQL_FAZCORD_DATABASE: faz-cord
          MYSQL_FAZDB_DATABASE: faz-db
        run: |
          cp .env-example .env
          pytest
