# This workflow will install Python dependencies, run tests and lint(todo) with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Stop default MySQL server (if any)
        run: sudo service mysql stop

      - name: Setup MariaDB
        run: |
          docker run \
          -e MYSQL_ROOT_PASSWORD=password \
          -e MYSQL_USER=faz \
          -e MYSQL_PASSWORD=password \
          -e MYSQL_FAZBOT_DATABASE=faz-bot_test \
          -e MYSQL_FAZDB_DATABASE=faz-db_test \
          -v ${GITHUB_WORKSPACE}/mysql/init:/docker-entrypoint-initdb.d \
          -d -p "3306:3306" mariadb:11.4.2

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          pip install -r requirements_dev.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_USER: faz
          MYSQL_PASSWORD: password
          MYSQL_FAZBOT_DATABASE: faz-bot
          MYSQL_FAZDB_DATABASE: faz-db
        run: |
          cp .env-example .env
          pytest
